---
title: "Sessions"
comments: false
---

## Session 0: Introduction and course overview

13:30-13:35

- Introduction to the course and the instructors (5 mins)

## Session 1: Forecasting

13:35-14:10

- Introduction to forecasting as an epidemiological problem (10 mins)
- Practice session: Visualising infectious disease forecasts (25 minutes)

## Session 2: Forecast evaluation

14:10-15:00

- An introduction to forecast evaluation (5 mins)
- Practice session: Evaluating forecasts from a range of models (40 mins)
- Wrap up (5 mins)

## Session 3: Evaluating forecasts from multiple models

15:10-15:50

- Why might we want to evaluate forecasts from multiple models? (5 mins)
- Practice session: Evaluating forecasts from multiple models (40 mins)
- Wrap up (5 mins)

*There is a coffee break at 15:30-15:40 you are welcome to attend this or keep working through the course material.*

## Session 4: Forecast ensembles

15:50-17:10

- Introduction to forecast ensembles (10 mins)
- Practice session: Creating forecast ensembles (60 mins)
- Wrap up (10 mins)

## Session 5: End of course summary

17:10-17:30

- Summary of the course (10 mins)
- Final discussion and closing (10 mins)
